language: haskell

before_install:
  - git submodule update --init --recursive

branches:
  only:
    - master

script:
  - cabal update && cabal install Cabal cabal-install && cabal configure --enable-tests && cabal build && cabal test
